<?php

namespace Marello\Bundle\ReturnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReturnEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ReturnEntityRepository extends EntityRepository
{
}
