<?php

namespace Marello\Bundle\MagentoBundle\Provider\Reader;

use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerAwareTrait;

use Oro\Bundle\OrganizationBundle\Entity\Organization;
use Oro\Bundle\ImportExportBundle\Reader\EntityReader;

class ProductCategoryExportReader extends EntityReader implements LoggerAwareInterface
{
    use LoggerAwareTrait;

    /**
     * {@inheritdoc}
     */
    protected function createSourceEntityQueryBuilder($entityName, Organization $organization = null, array $ids = [])
    {
        $qb = parent::createSourceEntityQueryBuilder($entityName, $organization, $ids);

        /*
        $qb->where(
            $qb->expr()->andX(
                $qb->expr()->neq("salesChannel.channelType", ":channelType"),
                $qb->expr()->isNotNull("salesChannel.integrationChannel")
            )
        );
        $qb->setParameter("channelType", MagentoChannelType::TYPE);
        */

        //TODO: filter based on channel

//        echo $qb->getQuery()->getSQL();
//        die("xxxxx");

        return $qb;
    }

    public function read()
    {
        $result = parent::read(); // TODO: Change the autogenerated stub

        return $result;
    }
}
