api:
    entity_aliases:
        Marello\Bundle\PricingBundle\Entity\ProductPrice:
            alias: marelloproductprice
            plural_alias: marelloproductprices

        Marello\Bundle\PricingBundle\Entity\ProductChannelPrice:
            alias: marelloproductchannelprice
            plural_alias: marelloproductchannelprices

        Marello\Bundle\PricingBundle\Entity\PriceType:
            alias: marellopricetype
            plural_alias: marellopricetypes

        Marello\Bundle\PricingBundle\Entity\AssembledPriceList:
            alias: marelloassembledpricelist
            plural_alias: marelloassembledpricelists

        Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList:
            alias: marelloassembledchannelpricelist
            plural_alias: marelloassembledchannelpricelists

    entities:
        Marello\Bundle\PricingBundle\Entity\AssembledPriceList:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/assembledpricelist.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        allow_array: true
                        property_path: product.sku
                        description: 'Filter prices by Product SKU'
                    currency:
                        data_type: string
                        property_path: currency
                        description: 'Filter prices by currency'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList:
            fields:
                saleschannel:
                    property_path: channel
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        allow_array: true
                        property_path: product.sku
                        description: 'Filter prices by Product SKU'
                    saleschannel:
                        data_type: string
                        property_path: channel.code
                        description: 'Filter prices by SalesChannel'
                    currency:
                        data_type: string
                        property_path: currency
                        description: 'Filter prices by currency'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\PriceType:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/pricetype.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\ProductPrice:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/productprice.md'
            fields:
                pricetype:
                    property_path: type
            filters:
                exclusion_policy: all
                fields:
                    pricetype:
                        data_type: string
                        property_path: type
                        description: 'Filter prices by PriceType'
                    product:
                        data_type: string
                        property_path: product.sku
                        allow_array: true
                        description: 'Filter prices by Product SKU'
                    currency:
                        data_type: string
                        description: 'Filter prices by currency'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter prices by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter prices by updated at'
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\ProductChannelPrice:
            fields:
                saleschannel:
                    property_path: channel
                pricetype:
                    property_path: type
            filters:
                exclusion_policy: all
                fields:
                    pricetype:
                        data_type: string
                        property_path: type
                        description: 'Filter prices by PriceType'
                    saleschannel:
                        data_type: string
                        property_path: channel.code
                        description: 'Filter prices by SalesChannel'
                    product:
                        data_type: string
                        property_path: product.sku
                        allow_array: true
                        description: 'Filter prices by Product SKU'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter prices by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter prices by updated at'
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false
