operations:
    marello_payment_add:
        label: marello.payment.button.add_payment.label
        applications: [default]
        acl_resource: [EDIT, $.data]
        order: 20
        routes:
            - marello_invoice_invoice_view
        attributes:
            invoice_paid_amount:
                label: marello.payment.total_paid.label
                type: float
            payment_method:
                label: marello.payment.payment_method.label
                type: string
            payment_date:
                label: marello.payment.payment_date.label
                type: object
                options:
                    class: \DateTime
            payment_reference:
                label: marello.payment.payment_reference.label
                type: string
            payment_details:
                label: marello.payment.payment_details.label
                type: string
            total_paid:
                label: marello.payment.total_paid.label
                type: object
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\Price
            action_result:
                label: 'result'
                type: array
        form_options:
            attribute_fields:
                payment_method:
                    form_type: Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodSelectType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
                payment_date:
                    form_type: Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
                payment_reference:
                    form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
                payment_details:
                    form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
                total_paid:
                    form_type: Marello\Bundle\OrderBundle\Form\Type\OrderTotalPaidType
                    options:
                        required: true
                        currency: $.data.currency
        frontend_options:
            options:
                width: 2000
            show_dialog: true
            template: '@MarelloPayment/Action/payment_popup.html.twig'
        preactions:
            - '@call_service_method':
                  service: marello_invoice.provider.invoice_paid_amount
                  method: getPaidAmount
                  method_parameters: [$.data]
                  attribute: $.invoice_paid_amount
        preconditions:
            '@and':
                - '@less': [$.invoice_paid_amount, $.data.grandTotal]
        actions:
            - '@call_service_method':
                  service: marello_payment.action.handler.add_payment
                  method: handleAction
                  method_parameters: [$.data, $.payment_method, $.payment_date, $.payment_reference, $.payment_details, $.total_paid.value]
                  attribute: $.action_result
            - '@flash_message':
                  message: $.action_result.message
                  type: $.action_result.type

    send_invoice_email:
        label: marello.invoice.action.send_invoice_email.label
        applications: [default]
        acl_resource: [EDIT, $.data]
        order: 10
        button_options:
            icon: fa-envelope
        routes:
            - marello_invoice_invoice_view
        frontend_options:
            show_dialog: true
            confirmation:
                title: marello.invoice.action.send_invoice_email.label
                message: marello.invoice.action.send_invoice_email.description
                message_parameters:
                    email: $.data.customer.email
                    name: $.data.customer.fullName
                component: oroui/js/standart-confirmation
        actions:
            - '@call_service_method':
                  service: oro_config.manager
                  method: get
                  method_parameters:
                      - 'marello_pdf.email_sender_email'
                      - false
                      - false
                      - '$.data.order.salesChannel'
                  attribute: '$.sender_email'
            - '@tree':
                  conditions:
                      '@not_empty': [ '$.sender_email' ]
                  actions:
                      - '@assign_value': ['$.receiver_email', '$.data.customer.email']
                      - '@assign_value': ['$.receiver_name', '$.data.customer.fullName']
                      - '@call_service_method':
                            service: oro_config.manager
                            method: get
                            method_parameters:
                                - 'marello_pdf.email_sender_name'
                                - false
                                - false
                                - '$.data.order.salesChannel'
                            attribute: '$.sender_name'
                      - '@call_service_method':
                            service: oro_config.manager
                            method: get
                            method_parameters:
                                - 'marello_pdf.email_bcc'
                                - false
                                - false
                                - '$.data.order.salesChannel'
                            attribute: '$.bcc'
                      - '@call_service_method':
                            service: translator
                            method: trans
                            method_parameters:
                                - 'marello.invoice.pdf.filename.label'
                                - { '%%invoiceType%%': '$.data.invoiceType', '%%entityNumber%%': '$.data.invoiceNumber' }
                            attribute: '$.filename'
                      - '@call_service_method':
                            service: marello_pdf.provider.render_parameters
                            method: getParams
                            method_parameters:
                                - '$.data'
                                - { config_scope: '$.data.order.salesChannel' }
                            attribute: '$.render_parameters'
                      - '@call_service_method':
                            service: marello_pdf.renderer.twig
                            method: renderBase64
                            method_parameters:
                                - '@MarelloInvoice/Pdf/invoice.html.twig'
                                - '$.render_parameters'
                            attribute: '$.invoice_pdf'
                      - '@send_email_template_attachment':
                            parameters:
                                from: { email: '$.sender_email', name: '$.sender_name' }
                                to: { email: '$.receiver_email', name: '$.receiver_name' }
                                template: marello_send_invoice
                                bcc: '$.bcc'
                                entity: '$.data'
                                context: '$.data.order'
                                attachments:
                                    - filename: '$.filename'
                                      body: '$.invoice_pdf'
                                      mimetype: 'application/pdf'
                      - '@flash_message':
                            type: 'success'
                            message: marello.invoice.action.send_invoice_email.success
                            message_parameters:
                                '%%email%%': '$.receiver_email'
            - '@tree':
                  conditions:
                      '@empty': [ '$.sender_email' ]
                  actions:
                      - '@flash_message':
                            type: 'error'
                            message: marello.invoice.action.send_invoice_email.error
