services:
    #form types
    marello_sales_form_type.saleschannel:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelType'
        arguments:
            - '@marello_productprice.pricing.form.event_listener.currency_subscriber'
        tags:
            - { name: form.type }

    marello_sales_form_type.saleschannel_type_select:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelTypeSelectType'
        tags:
            - { name: form.type }

    marello_sales_form_type.saleschannel_type:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelTypeType'
        tags:
            - { name: form.type }

    marello_sales_form_type.saleschannelgroup:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelGroupType'
        tags:
            - { name: form.type }

    marello_sales_form_type.saleschannel_multi_select:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelMultiSelectType'
        arguments:
            - '@marello_sales.form.data_transformer.sales_channel'
        tags:
            - { name: form.type }

    marello_sales_form_type.system_group_saleschannel_multi_select:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SystemGroupSalesChannelMultiselectType'
        arguments:
            - '@marello_sales.form.data_transformer.sales_channel'
        tags:
            - { name: form.type }

    marello_sales_form_type.saleschannel_select:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelSelectType'
        tags:
            - { name: form.type }

    marello_sales.form.type.sales_channel_select_api:
        class: 'Marello\Bundle\SalesBundle\Form\Type\SalesChannelSelectApiType'
        arguments:
            - '@marello_sales.form.data_transformer.sales_channel_to_code'
        tags:
            - { name: form.type }

    #form handlers
    marello_sales.saleschannel_form.handler:
        class: 'Marello\Bundle\SalesBundle\Form\Handler\SalesChannelHandler'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: oro_form.form.handler, alias: marello_sales.saleschannel_form.handler }

    marello_sales.saleschannelgroup_form.handler:
        class: 'Marello\Bundle\SalesBundle\Form\Handler\SalesChannelGroupHandler'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.acl_helper'
        tags:
            - { name: oro_form.form.handler, alias: marello_sales.saleschannelgroup_form.handler }

    #data transformer
    marello_sales.form.data_transformer.sales_channel:
        class: Oro\Bundle\FormBundle\Form\DataTransformer\EntitiesToIdsTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'MarelloSalesBundle:SalesChannel'

    marello_sales.form.data_transformer.sales_channel_to_code:
        class: Marello\Bundle\SalesBundle\Form\DataTransformer\SalesChannelToCodeTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
