imports:
    - { resource: controllers.yml }

parameters:
    marello_payment_term.method.identifier_prefix.payment_term: 'payment_term'
    marello_payment_term.integration.channel.type: 'payment_term'
    marello_payment_term.integration.transport.type: 'payment_term'

services:
    marello_payment_term.provider.payment_term:
        class: 'Marello\Bundle\PaymentTermBundle\Provider\PaymentTermProvider'
        arguments:
            - '@oro_config.manager'
            - '@oro_entity.doctrine_helper'

    marello_payment_term.provider.payment_term_delete_permission:
        class: 'Marello\Bundle\PaymentTermBundle\Provider\PaymentTermDeletePermissionProvider'
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@marello_payment_term.provider.payment_term'

    marello_payment_term.action_permissions.payment_term:
        class: 'Marello\Bundle\PaymentTermBundle\Datagrid\PaymentTermActionPermissionProvider'
        public: true
        arguments:
            - '@marello_payment_term.provider.payment_term_delete_permission'

    marello_payment_term.integration.channel:
        class: 'Marello\Bundle\PaymentTermBundle\Integration\PaymentTermChannelType'
        public: true
        tags:
            - { name: oro_integration.channel, type: payment_term }

    marello_payment_term.integration.transport:
        class: 'Marello\Bundle\PaymentTermBundle\Integration\PaymentTermTransport'
        public: false
        tags:
            - { name: oro_integration.transport, type: payment_term, channel_type: payment_term }

    marello_payment_term.method.identifier_generator.method:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%marello_payment_term.method.identifier_prefix.payment_term%'

    marello_payment_term.factory.method:
        class: 'Marello\Bundle\PaymentTermBundle\Method\Factory\PaymentTermMethodFromChannelFactory'
        public: false
        arguments:
            - '@marello_payment_term.method.identifier_generator.method'
            - '@oro_locale.helper.localization'
            - '@oro_integration.provider.integration_icon'

    marello_payment_term.payment_method_provider.payment_term:
        class: 'Marello\Bundle\PaymentTermBundle\Method\Provider\PaymentTermMethodProvider'
        public: false
        arguments:
            - '%marello_payment_term.integration.channel.type%'
            - '@oro_entity.doctrine_helper'
            - '@marello_payment_term.factory.method'
        tags:
            - { name: marello_payment.payment_method_provider }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\IntegrationBundle\Entity\Channel', event: postLoad }

    marello_payment_term.event_listener.payment_term_method_view:
        class: 'Marello\Bundle\PaymentTermBundle\EventListener\PaymentTermMethodViewListener'
        arguments:
            - '@marello_payment_term.provider.payment_term'
        tags:
            - { name: kernel.event_listener, event: marello_payment.applicable_payment_method_view, method: onApplicablePaymentMethodView }

    marello_payment_term.twig.payment_term_extension:
        class: 'Marello\Bundle\PaymentTermBundle\Twig\PaymentTermExtension'
        public: false
        arguments:
            - '@marello_payment_term.provider.payment_term'
            - '@oro_locale.helper.localization'
        tags:
            - { name: twig.extension }
