imports:
    - { resource: controllers.yml }

services:
    marello_packing.mapper.order_to_packingslip:
        class: 'Marello\Bundle\PackingBundle\Mapper\OrderToPackingSlipMapper'
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'

    marello_packing.event_listener.create_packing_slip:
        class: 'Marello\Bundle\PackingBundle\EventListener\CreatePackingSlipEventListener'
        arguments:
            - '@marello_packing.mapper.order_to_packingslip'
            - '@oro_entity.doctrine_helper'
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: extendable_action.create_packingslip, method: onCreatePackingSlip, priority: 10 }

    marello_packing.listener.datagrid.packing_slip_grid_address_filter_listener:
        class: 'Marello\Bundle\PackingBundle\EventListener\Datagrid\GridAddressFilterListener'
        arguments:
            - '@oro_locale.dql.formatter.name'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-packingslips, method: onBuildBefore }

    marello_packing.listener.datagrid.packingslipitems_batchnumbers_column_listener:
        class: 'Marello\Bundle\PackingBundle\EventListener\Datagrid\PackingslipItemsBatchNumbersColumnListener'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.marello-packingslip-items, method: onBuildAfter }

    marello_packing.listener.doctrine.packing_slip_item_status:
        class: 'Marello\Bundle\PackingBundle\EventListener\Doctrine\PackingSlipItemStatusListener'
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
#            - { name: kernel.event_listener, event: extendable_action.order_ship, method: onOrderShipped }