#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Command\LintCommand;
use Marello\Cli\Command\InitRemoteRepositoriesCommand;
use Marello\Cli\Command\RemoveRemoteRepositoriesCommand;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->addCommands(
    [
        new LintCommand(),
        new InitRemoteRepositoriesCommand(),
        new RemoveRemoteRepositoriesCommand()
    ]
);

$application->run();
