#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Command\LintCommand;
use Marello\Cli\Command\RemoteInitCommand;
use Marello\Cli\Command\RemoteRemoveCommand;
use Marello\Cli\Command\RemoteSyncCommand;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->addCommands(
    [
        new LintCommand(),
        new RemoteInitCommand(),
        new RemoteRemoveCommand(),
        new RemoteSyncCommand()
    ]
);

$application->run();
