datagrids:
    marello-paymentterm-grid:
        source:
            type: orm
            query:
                select:
                    - p.id
                    - p.code
                    - p.term
                    - p
                from:
                    - { table: 'MarelloPaymentTermBundle:PaymentTerm', alias: p }
        columns:
            label:
                label: marello.paymentterm.labels.label
                type: twig
                frontend_type: html
                template: '@MarelloPaymentTerm/PaymentTerm/Datagrid/label.html.twig'
            code:
                label: marello.paymentterm.code.label
                frontend_type: string
            term:
                label: marello.paymentterm.term.label
                type: twig
                frontend_type: html
                template: '@MarelloPaymentTerm/PaymentTerm/Datagrid/term.html.twig'
        filters:
            columns:
                label:
                    type: string
                    data_name: label_localized
                code:
                    type: string
                    data_name: code
                term:
                    type: number-range
                    data_name: term
        sorters:
            columns:
                label:
                    data_name: label_localized
                code:
                    data_name: code
                term:
                    data_name: term
            default:
                label: 'ASC'
        properties:
            id: ~
            view_link:
                type: url
                route: marello_paymentterm_paymentterm_view
                params: [ id ]
            update_link:
                type: url
                route: marello_paymentterm_paymentterm_update
                params: [ id ]
            label_localized:
                type: localized_value
                data_name: p.labels
                allow_empty: true
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                link: view_link
                icon: eye
                acl_recource: marello_paymentterm_paymentterm_view
                rowAction: true
            update:
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
                acl_resource: marello_paymentterm_paymentterm_update
        action_configuration: ['@marello_payment_term.action_permissions.payment_term', 'getActionPermissions']
        options:
            entityHint: marello.paymentterm.entity_plural_label
            entity_pagination: true
            mass_actions:
                delete:
                    enabled: false
