<?php

namespace Marello\Bundle\TaxBundle\Entity\Repository;

/**
 * ProductChannelTaxRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChannelTaxRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
