<?php

namespace Marello\Bundle\TaxBundle\Entity\Repository;

/**
 * TaxRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRateRepository extends \Doctrine\ORM\EntityRepository
{
}
